name: 'Build & Test'

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - run: npm install
    # - run: npm run compile
    - run: npm run test